### ISSUE TITLE
The decimal precision page is not in an appropriate spot

### ISSUE THREAD

**Issue by rutrum** [rutrum/cpp-book#1]
I don't believe this should be a reference page, especially since it is written in a narrative style, which I think should be in a different part of the book.

However, while the content is about C++, it steps outside the bounds of those needed for the CS142 class, I don't believe it has a place yet in the current state of this book.  Maybe this material could be expanded to a different source?

**Comment by troywiegand** [comment]
A student on Wednesday told me that needed to only go to 3 decimal places for a project they were doing. (Sligh) This should be in this book somewhere. I could strip the printf information and add some context at the beginning, but setpercision should be there in some form

**Comment by rutrum** [comment]
Understandable.  I'm not sure it belongs in references, I would put it in the root directory for now.  I would absolutely remove printf and the % notation, for consistency.

**Comment by troywiegand** [comment]
Yes sir
